[project]
name = "etl-ingestion-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.17.2",
    "pydantic>=2.12.5",
    "sqlalchemy-utils>=0.42.1",
    "sqlalchemy[asyncio]>=2.0.45",
]
